//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scholarship.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public string STUDENT_ID { get; set; }
        public string NAME { get; set; }
        public string COURSE { get; set; }
        public string EDUCATIONAL { get; set; }
        public Nullable<decimal> AGE { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<decimal> COLLEGE_ID { get; set; }
        public string M_NAME { get; set; }
        public string F_NAME { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> DOA { get; set; }
    
        public virtual COLLEGE COLLEGE { get; set; }
    }
}
